/* =========================================================================
 * xscugic_g.c — XScuGic configuration table for the Zynq-7000 GIC.
 *
 * This file is normally auto-generated by Vitis Workbench from the .hwh.
 * For our WSL2 standalone build of demo_ascii.elf we provide it by hand,
 * with one entry pointing at the single GIC instance on the Zynq Cortex-A9
 * MPCore. The entry IDs and base addresses come from xparameters.h.
 *
 * Not used on Windows Vitis Workbench (Vitis generates its own copy).
 * ========================================================================= */
#include "xparameters.h"
#include "xscugic.h"

XScuGic_Config XScuGic_ConfigTable[XPAR_XSCUGIC_NUM_INSTANCES] = {
    {
        XPAR_PS7_SCUGIC_0_DEVICE_ID,        /* DeviceId         */
        XPAR_PS7_SCUGIC_0_BASEADDR,         /* CpuBaseAddress   */
        XPAR_PS7_SCUGIC_0_DIST_BASEADDR,    /* DistBaseAddress  */
        { { (Xil_InterruptHandler)0, (void *)0 } }   /* HandlerTable[0] */
    }
};
