# =============================================================================
# build_v_tpg_test_bitstream.tcl — End-to-end Vivado bitstream build flow that
# demonstrates how to extend the cgra_pynq_base BD with a v_tpg test pattern
# source, then run synth + impl to produce a new bitstream + ps7_init.
#
# Thesis Chapter 5: "Vivado-Centric Bitstream Build Procedure"
# ───────────────────────────────────────────────────────────────────────────
#   1. Take the silicon-validated base.tcl (write_bd_tcl export from the
#      working CGRA_PYNQ_clean project) as input.
#   2. Create a fresh project in WSL.
#   3. Re-create the working BD via source base.tcl.
#   4. Source add_v_tpg_test_pattern.tcl to graft v_tpg + axis_switch onto
#      the HDMI-in capture pipeline.
#   5. Generate wrapper, run synth + impl, write_bitstream + report_power.
#   6. Export ps7_init.tcl for bare-metal use.
#
# Stages selectable via env CGRA_VTPG_STAGE:
#   A = BD validate only      (~5 min, lo mem)
#   B = + synth_1             (~20 min, ~3 GB mem)
#   C = + impl + bitstream    (~50 min, ~5 GB mem)   ← default
#
# Usage:
#   CGRA_VTPG_STAGE=A vivado -mode batch -source \
#       scripts/build_v_tpg_test_bitstream.tcl
# =============================================================================

puts "==========================================================="
puts " V_TPG TEST-PATTERN BITSTREAM BUILD (Vivado [version -short])"
puts "==========================================================="

proc _env_or_default {name def} {
    if {[info exists ::env($name)]} { return $::env($name) }
    return $def
}

# Paths
set BASE_TCL     [_env_or_default CGRA_BASE_TCL "/mnt/c/Users/thanh/Desktop/CGRA_PYNQ_clean/base.tcl"]
set PYNQ_REPO    [_env_or_default CGRA_PYNQ_REPO "/mnt/c/Users/thanh/Desktop/PYNQ_repo/boards/ip"]
set CGRA_IPREPO  [_env_or_default CGRA_CGRA_IPREPO "/mnt/c/Users/thanh/Desktop/CGRA_PYNQ_clean/cgra_ip_repo"]
set PROJECT_DIR  [_env_or_default CGRA_VTPG_VPROJ "$::env(HOME)/vivado_projects/cgra_vtpg"]
set STAGE        [_env_or_default CGRA_VTPG_STAGE "C"]
set PATCH_TCL    [_env_or_default CGRA_VTPG_PATCH "[file normalize [file dirname [info script]]]/add_v_tpg_test_pattern.tcl"]

puts "  base.tcl    : $BASE_TCL"
puts "  PYNQ ip     : $PYNQ_REPO"
puts "  CGRA ip     : $CGRA_IPREPO"
puts "  project     : $PROJECT_DIR"
puts "  patch       : $PATCH_TCL"
puts "  stage       : $STAGE  (A=BD-only, B=synth, C=full impl+bitstream)"

foreach req [list $BASE_TCL $PYNQ_REPO $CGRA_IPREPO $PATCH_TCL] {
    if {![file exists $req]} {
        error "Missing required path: $req"
    }
}

# Keep WSL2 happy: cap parallel synth threads.
set_param general.maxThreads 2

# ----- 1. Create project ----------------------------------------------------
puts "\n=== 1. Create Vivado project ==="
file delete -force $PROJECT_DIR
file mkdir $PROJECT_DIR
create_project -force cgra_vtpg $PROJECT_DIR -part xc7z020clg400-1
set_property target_language Verilog [current_project]

# ----- 2. IP repos ----------------------------------------------------------
puts "\n=== 2. IP repository paths ==="
set_property ip_repo_paths [list $PYNQ_REPO $CGRA_IPREPO] [current_project]
update_ip_catalog

# ----- 3. Source base.tcl (re-creates the working BD) -----------------------
puts "\n=== 3. Source base.tcl (re-creating cgra_pynq_base BD) ==="
# base.tcl was generated by write_bd_tcl in Vivado 2024.1 with strict
# version checks; patch a temp copy to 2025.1. It also references the
# PYNQ overlay metadata via ${overlay_name} — must be set first.
set overlay_name "base"
set tmp_base "$PROJECT_DIR/base_patched.tcl"
set fp [open $BASE_TCL r]
set src [read $fp]; close $fp
regsub -all {set scripts_vivado_version 2024.1} $src \
    "set scripts_vivado_version 2025.1" src
regsub -all {\$\{overlay_name\}} $src "base" src
set fp [open $tmp_base w]
puts $fp $src; close $fp
puts "  patched 2024.1 → 2025.1 + overlay_name → \"base\" in $tmp_base"
if {[catch {source $tmp_base} err]} {
    puts "  base.tcl raised: $err"
    puts "  Inspecting current BD state — may have partially completed."
}

# base.tcl creates a BD called `base` but doesn't leave it open in current
# scope. Re-open explicitly.
set bd_name "base"
set bd_files [get_files -quiet ${bd_name}.bd]
if {[llength $bd_files] == 0} {
    error "BD ${bd_name}.bd not found in project after sourcing base.tcl"
}
open_bd_design [lindex $bd_files 0]
puts "  BD now in scope: $bd_name"

# ----- 4. Apply v_tpg patch -------------------------------------------------
puts "\n=== 4. Source add_v_tpg_test_pattern.tcl ==="
source $PATCH_TCL

# ----- 5. Generate wrapper + add constraints --------------------------------
puts "\n=== 5. make_wrapper + constraints ==="
make_wrapper -files [get_files ${bd_name}.bd] -top -import
set_property top ${bd_name}_wrapper [current_fileset]

# Use the PYNQ-Z2 master XDC from the PYNQ repo — it constrains every
# I/O the BD exposes (audio codec, switches, buttons, HDMI etc.).
# Falling back to the minimal HDMI-only XDC would trip UCIO-1/NSTD-1
# at write_bitstream time.
set xdc_candidates [list \
    {/mnt/c/Users/thanh/Desktop/PYNQ_repo/boards/Pynq-Z2/base/vivado/constraints/base.xdc} \
    "[file normalize [file dirname [info script]]/..]/01_bench/constrs_pynq_z2.xdc"]
foreach XDC $xdc_candidates {
    if {[file exists $XDC]} {
        add_files -fileset constrs_1 -norecurse $XDC
        puts "  Added constraints: $XDC"
        break
    }
}
update_compile_order -fileset sources_1

# ----- 6. Stage A: validate only -------------------------------------------
puts "\n=== 6. validate_bd_design ==="
save_bd_design

if {$STAGE eq "A"} {
    puts "\n=========================================="
    puts " Stage A complete — BD validates."
    puts " Re-run with CGRA_VTPG_STAGE=B (synth) or C (impl)."
    puts "=========================================="
    return
}

# ----- 7. Stage B: synth_1 -------------------------------------------------
puts "\n=== 7. launch_runs synth_1 -jobs 2 ==="
launch_runs synth_1 -jobs 2
wait_on_run synth_1
set synth_status [get_property STATUS [get_runs synth_1]]
puts "  synth_1 status: $synth_status"
if {![string match "*Complete*" $synth_status] || [string match "*ERROR*" $synth_status]} {
    error "Synthesis failed — see $PROJECT_DIR/cgra_vtpg.runs/synth_1/runme.log"
}
open_run synth_1 -name synth_1
report_utilization -file $PROJECT_DIR/synth_util.rpt
puts "  Synth utilisation → $PROJECT_DIR/synth_util.rpt"

if {$STAGE eq "B"} {
    puts "\n=========================================="
    puts " Stage B complete — synth_1 OK."
    puts " Re-run with CGRA_VTPG_STAGE=C for impl + bitstream."
    puts "=========================================="
    return
}

# ----- 8. Stage C: impl + write_bitstream -----------------------------------
puts "\n=== 8. launch_runs impl_1 -to_step write_bitstream -jobs 2 ==="
launch_runs impl_1 -to_step write_bitstream -jobs 2
wait_on_run impl_1
set impl_status [get_property STATUS [get_runs impl_1]]
puts "  impl_1 status: $impl_status"
if {![string match "*Complete*" $impl_status]} {
    error "Impl failed — see $PROJECT_DIR/cgra_vtpg.runs/impl_1/runme.log"
}

open_run impl_1 -name impl_1
report_utilization        -file $PROJECT_DIR/impl_util.rpt
report_timing_summary     -file $PROJECT_DIR/impl_timing.rpt -warn_on_violation
report_drc                -file $PROJECT_DIR/impl_drc.rpt
report_power              -file $PROJECT_DIR/impl_power.rpt

set wns [get_property SLACK [get_timing_paths -delay_type max -nworst 1]]
set whs [get_property SLACK [get_timing_paths -delay_type min -nworst 1]]
puts ""
puts "==========================================================="
puts " V_TPG TEST-PATTERN BITSTREAM BUILD COMPLETE"
puts "==========================================================="
puts " Bitstream  : $PROJECT_DIR/cgra_vtpg.runs/impl_1/${bd_name}_wrapper.bit"
puts " WNS        : $wns"
puts " WHS        : $whs"
puts " Util       : $PROJECT_DIR/impl_util.rpt"
puts " Timing     : $PROJECT_DIR/impl_timing.rpt"
puts " DRC        : $PROJECT_DIR/impl_drc.rpt"
puts " Power      : $PROJECT_DIR/impl_power.rpt"
puts ""
puts " Stage the artefacts into the project repo:"
puts "   cp $PROJECT_DIR/cgra_vtpg.runs/impl_1/${bd_name}_wrapper.bit \\"
puts "      bitstreams/cgra_vtpg_test.bit"
puts "   cp [glob -nocomplain $PROJECT_DIR/cgra_vtpg.gen/sources_1/bd/${bd_name}/ip/*processing_system7*/ps7_init.tcl] \\"
puts "      scripts/ps7_init_vtpg.tcl"
puts "==========================================================="
