# =============================================================================
# vitis_launch_with_clear.tcl — canonical xsct launch sequence with DAP
# escalation. Use this for ALL silicon-validation runs.
#
# Per senior-eng post-mortem 2026-05-28 (06_doc/senior_arch_review_*.md +
# memory/feedback_dap_escalation_fpga_clear.md):
#
#   * fpga -clear  goes BEFORE fpga -file. Wipes any PL state that might
#                  be holding an outstanding AXI transaction.
#   * ps7_init.tcl is sourced from the .xsa's _ide/psinit/ directory.
#                  NEVER use the legacy scripts/ps7_init.tcl (stale).
#   * MMIO ping-pong (bench_smoke.elf) is the first ELF run after init.
#                  Real workload only runs AFTER smoke passes.
#
# Usage (via xsct):
#   CGRA_XSA_DIR=/tmp/cgra_vitis_ws/<app>/_ide   \
#   CGRA_BIT=bitstreams/cgra_top.bit             \
#   CGRA_ELF=/tmp/cgra_vitis_ws/<app>/Debug/<app>.elf \
#   xsct scripts/vitis_launch_with_clear.tcl
# =============================================================================

proc _env_or {name def} {
    if {[info exists ::env($name)]} { return $::env($name) }
    return $def
}

set XSA_DIR  [_env_or CGRA_XSA_DIR   /tmp/cgra_vitis_ws/bench_mac_micro_v2/_ide]
set BIT      [_env_or CGRA_BIT        bitstreams/cgra_top.bit]
set ELF      [_env_or CGRA_ELF        /tmp/cgra_vitis_ws/bench_mac_micro_v2/Debug/bench_mac_micro_v2.elf]
set PS_INIT  $XSA_DIR/psinit/ps7_init.tcl

puts "==========================================================="
puts " VITIS LAUNCH (with DAP escalation)"
puts "==========================================================="
puts "  Bitstream : $BIT"
puts "  ps7_init  : $PS_INIT"
puts "  ELF       : $ELF"
puts "==========================================================="

# ----- Connect + clear DAP error if any -----
connect -url tcp:localhost:3121
configparams force-mem-accesses 1
catch {targets -set -filter {name =~ "DAP*"}}
catch {rst -dap}
after 500

# ----- KEY ESCALATION STEP: wipe the PL to break any wedged AXI state -----
# Without this, a previous run's CGRA DMA holding VALID can keep the PS
# interconnect stuck even after rst -dap.
catch {targets -set -filter {name =~ "xc7z020"}}
puts "\n\[Pre\] fpga -clear (wipe PL config to drain wedged AXI state)..."
catch {fpga -clear} e_clear
puts "  fpga -clear result: '$e_clear'"
after 500

# ----- Load the requested bitstream -----
puts "\n\[1\] fpga -file $BIT"
if {[catch {fpga -file $BIT} err]} { puts "ERROR: fpga -file: $err"; exit 1 }
after 1500

# ----- Halt A9 #0 and run the FRESH ps7_init from .xsa -----
catch {targets -set -filter {name =~ "ARM*Cortex-A9*#0"}}
catch {stop} e_stop
puts "\n\[2\] stop: '$e_stop' (Already stopped is fine)"
after 300

puts "\n\[3\] source $PS_INIT  (fresh, generated by Vivado for THIS BD)"
if {[catch {source $PS_INIT} err]} { puts "ERROR: source ps7_init: $err"; exit 1 }
if {[catch {ps7_init}        err]} { puts "ERROR: ps7_init: $err"; exit 1 }
if {[catch {ps7_post_config} err]} { puts "ERROR: ps7_post_config: $err"; exit 1 }
puts "  PS-7 init complete."

# ----- Download + run -----
puts "\n\[4\] dow $ELF"
if {[catch {dow $ELF} err]} { puts "ERROR: dow: $err"; exit 1 }

puts "\n\[5\] con (launch)"
catch {con} ec
puts "  con: '$ec'"
puts "\nELF running. UART output should appear on /dev/ttyUSB1."
exit
