# =============================================================================
# vitis_launch_with_clear.tcl — canonical xsct launch sequence with DAP
# escalation. Use this for ALL silicon-validation runs.
#
# Per senior-eng post-mortem 2026-05-28 (06_doc/senior_arch_review_*.md +
# memory/feedback_dap_escalation_fpga_clear.md):
#
#   * fpga -clear  goes BEFORE fpga -file. Wipes any PL state that might
#                  be holding an outstanding AXI transaction.
#   * ps7_init.tcl is sourced from the .xsa's _ide/psinit/ directory.
#                  NEVER use the legacy scripts/ps7_init.tcl (stale).
#   * MMIO ping-pong (bench_smoke.elf) is the first ELF run after init.
#                  Real workload only runs AFTER smoke passes.
#
# Usage (via xsct):
#   CGRA_XSA_DIR=/tmp/cgra_vitis_ws/<app>/_ide   \
#   CGRA_BIT=bitstreams/cgra_top.bit             \
#   CGRA_ELF=/tmp/cgra_vitis_ws/<app>/Debug/<app>.elf \
#   xsct scripts/vitis_launch_with_clear.tcl
# =============================================================================

proc _env_or {name def} {
    if {[info exists ::env($name)]} { return $::env($name) }
    return $def
}

set XSA_DIR  [_env_or CGRA_XSA_DIR   /tmp/cgra_vitis_ws/bench_mac_micro_v2/_ide]
set BIT      [_env_or CGRA_BIT        bitstreams/cgra_top.bit]
set ELF      [_env_or CGRA_ELF        /tmp/cgra_vitis_ws/bench_mac_micro_v2/Debug/bench_mac_micro_v2.elf]
set PS_INIT  $XSA_DIR/psinit/ps7_init.tcl

puts "==========================================================="
puts " VITIS LAUNCH (with DAP escalation)"
puts "==========================================================="
puts "  Bitstream : $BIT"
puts "  ps7_init  : $PS_INIT"
puts "  ELF       : $ELF"
puts "==========================================================="

# ----- Connect + light recovery -----
# NOTE: `rst -system` works to unwedge A9 BUT also resets FCLK0/PL state,
# leaving the CGRA unclocked → APB hangs on next access. So we use a
# lighter recovery here and rely on power-cycle for hard wedges.
connect
configparams force-mem-accesses 1
catch {targets -set -filter {name =~ "DAP*"}}
catch {rst -dap}
after 500

# ----- NOTE: fpga -clear is NOT a valid xsct option in Vitis 2025.1.
# rst -processor unblocks a stuck while(1) but then breaks dow with
# "Cannot flush CPU cache" (verified 2026-05-28). The cleanest sequence
# is to just let `fpga -file` reset the PL and the implicit `stop` halt
# the A9 — both verified working in run bi6xwgyjq (2026-05-28 14:48).
#
# If the A9 is stuck from a prior run, run this BEFORE the launch script:
#     xsct -eval 'connect; targets -set -filter {name =~ "ARM*A9*#0"}; rst -processor; exit'
# wait ~1s, then re-launch.

# ----- Load the requested bitstream -----
puts "\n\[1\] fpga -file $BIT"
if {[catch {fpga -file $BIT} err]} { puts "ERROR: fpga -file: $err"; exit 1 }
after 1500

# ----- Halt A9 #0 and run the FRESH ps7_init from .xsa -----
# Aggressive halt: prior ELF runs leave A9 in a state where the initial
# `stop` times out. Multi-retry with rst -dap between attempts unwedges
# the AP-transaction-error sticky bit. Validated 2026-05-28.
set halted 0
for {set i 0} {$i < 5} {incr i} {
    catch {targets -set -filter {name =~ "DAP*"}}
    catch {rst -dap}
    after 400
    catch {targets -set -filter {name =~ "ARM*Cortex-A9*#0"}}
    if {![catch {stop} err]} {
        puts "\n\[2\] stop: succeeded on attempt $i"
        set halted 1
        break
    }
    puts "\n\[2\] stop attempt $i: '$err' — retrying after rst -dap"
}
if {!$halted} {
    puts "WARNING: stop failed after 5 retries — ps7_init may fail"
}
after 300

puts "\n\[3\] source $PS_INIT  (fresh, generated by Vivado for THIS BD)"
if {[catch {source $PS_INIT} err]} { puts "ERROR: source ps7_init: $err"; exit 1 }
if {[catch {ps7_init}        err]} { puts "ERROR: ps7_init: $err"; exit 1 }
if {[catch {ps7_post_config} err]} { puts "ERROR: ps7_post_config: $err"; exit 1 }
puts "  PS-7 init complete."

# ----- Download + run -----
puts "\n\[4\] dow $ELF"
if {[catch {dow $ELF} err]} { puts "ERROR: dow: $err"; exit 1 }

puts "\n\[5\] con (launch)"
catch {con} ec
puts "  con: '$ec'"
puts "\nELF running. UART output should appear on /dev/ttyUSB1."
exit
