#!/usr/bin/env bash
# =============================================================================
# run_scenarios.sh — orchestrate the three Chapter 5 sample-waveform runs.
#
# For each of {DMA, CUMAC, FCGROUP} this script invokes Cadence Xcelium to:
#   1. compile RTL + tb_wave_scenarios.sv via xmvlog
#   2. elaborate worklib.tb_wave_scenarios with -access +rwc into snap_wave
#   3. run xmsim three times with different +SCENARIO= plusargs
#
# Output: three SHM databases written into 03_sim/scenarios/ —
#   wave_dma.shm, wave_cumac.shm, wave_fcgroup.shm
#
# Prerequisites:
#   - Cadence Xcelium installed and the env script sourced so that
#     xmvlog/xmelab/xmsim are on PATH. This script does NOT source any
#     vendor env file; do `source <xcelium-install>/tools/bin/setup.csh`
#     (or your local equivalent) before invoking.
#
# Usage:
#   bash 01_bench/scenarios/run_scenarios.sh
# =============================================================================
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SRC_DIR="$PROJECT_ROOT/00_src"
BSG_DIR="$SRC_DIR/bsg_mem"
TB_DIR="$PROJECT_ROOT/01_bench"
SCEN_DIR="$TB_DIR/scenarios"
SIM_DIR="$PROJECT_ROOT/03_sim/scenarios"
LOG_DIR="$PROJECT_ROOT/02_log"

mkdir -p "$SIM_DIR" "$LOG_DIR"
cd "$SIM_DIR"

# ----- 0. Sanity check tools --------------------------------------------------
for t in xmvlog xmelab xmsim; do
  command -v "$t" >/dev/null 2>&1 || {
    echo "[ERROR] $t not on PATH — source your Cadence Xcelium setup script first." >&2
    exit 2
  }
done

# ----- 1. Build the file-list (flist) for compilation --------------------------
FLIST="$SIM_DIR/flist_wave"
{
  echo "// auto-generated by run_scenarios.sh"
  echo "-sv"
  echo "-incdir $SRC_DIR"
  echo "-incdir $BSG_DIR"
  echo "-incdir $TB_DIR"
  echo "-incdir $TB_DIR/include"
  echo "-incdir $SCEN_DIR"
  echo
  echo "// BSG memory primitives first"
  find "$BSG_DIR" -maxdepth 1 \( -name '*.sv' -o -name '*.v' \) | sort
  echo
  echo "// CGRA RTL sources"
  find "$SRC_DIR" -maxdepth 1 \( -name '*.sv' -o -name '*.v' \) | sort
  echo
  echo "// Scenario testbench"
  echo "$SCEN_DIR/tb_wave_scenarios.sv"
} > "$FLIST"

echo "[1/3] xmvlog compile..."
xmvlog -sv -f "$FLIST" -define XCELIUM 2>&1 \
    | tee "$LOG_DIR/wave_compile.log" | tail -20

# ----- 2. Elaborate once with the testbench as top -----------------------------
echo "[2/3] xmelab elaboration..."
xmelab -timescale 1ns/1ps \
       -access +rwc \
       -snapshot snap_wave \
       worklib.tb_wave_scenarios 2>&1 \
    | tee "$LOG_DIR/wave_elab.log" | tail -10

# ----- 3. Run xmsim three times, one per scenario ------------------------------
run_one () {
  local scen="$1"        # DMA | CUMAC | FCGROUP
  local shm_name="wave_${scen,,}.shm"   # lowercase
  echo "[3/3] xmsim SCENARIO=$scen → $shm_name"
  rm -rf "$SIM_DIR/$shm_name"
  xmsim snap_wave +SCENARIO="$scen" 2>&1 \
      | tee "$LOG_DIR/wave_${scen,,}.log" | tail -10
}

run_one DMA
run_one CUMAC
run_one FCGROUP

echo
echo "Done. SHM databases:"
for s in dma cumac fcgroup; do
  printf "  %s/wave_%s.shm\n" "$SIM_DIR" "$s"
done
echo
echo "View in SimVision, e.g.:"
echo "  cd $SIM_DIR && simvision wave_dma.shm/wave_dma.trn -input ${SCEN_DIR}/wave_restore.tcl"
